const Teachers_test = () => {
  const teacher = [
    {
      id: 1,
      first_name: "Ruthie",
      last_name: "Sarvar",
      email: "rsarvar0@gmpg.org",
      gender: "Male",
      music: "jazz",
      image: "https://randomuser.me/api/portraits/women/40.jpg",
    },
    {
      id: 2,
      first_name: "Pru",
      last_name: "Saer",
      email: "psaer1@issuu.com",
      gender: "Male",
      music: "rap",
      image: "https://randomuser.me/api/portraits/men/40.jpg",
    },
    {
      id: 3,
      first_name: "Nigel",
      last_name: "Quiney",
      email: "nquiney2@nih.gov",
      gender: "Male",
      music: "pop",
      image: "https://randomuser.me/api/portraits/men/41.jpg",
    },
    {
      id: 4,
      first_name: "Sherilyn",
      last_name: "Hardaway",
      email: "shardaway3@wp.com",
      gender: "Female",
      music: "electronic",
      image: "https://randomuser.me/api/portraits/women/41.jpg",
    },
    {
      id: 5,
      first_name: "Dorey",
      last_name: "Richfield",
      email: "drichfield4@noaa.gov",
      gender: "Male",
      music: "blues",
      image: "https://randomuser.me/api/portraits/men/42.jpg",
    },
    {
      id: 6,
      first_name: "Orella",
      last_name: "Cary",
      email: "ocary5@biglobe.ne.jp",
      gender: "Female",
      music: "raggae",
      image: "https://randomuser.me/api/portraits/women/43.jpg",
    },
    {
      id: 7,
      first_name: "Mary",
      last_name: "Valasek",
      email: "mvalasek6@ox.ac.uk",
      gender: "Male",
      music: "latin",
      image: "https://randomuser.me/api/portraits/men/43.jpg",
    },
    {
      id: 8,
      first_name: "Violante",
      last_name: "Sidden",
      email: "vsidden7@edublogs.org",
      gender: "Male",
      music: "rock",
      image: "https://randomuser.me/api/portraits/men/44.jpg",
    },
    {
      id: 9,
      first_name: "Renaldo",
      last_name: "Rown",
      email: "rrown8@ca.gov",
      gender: "Male",
      image: "https://randomuser.me/api/portraits/men/45.jpg",
    },
    {
      id: 10,
      first_name: "Waverly",
      last_name: "Ranner",
      email: "wranner9@senate.gov",
      gender: "Male",
      music: "classical",
      image: "https://randomuser.me/api/portraits/men/46.jpg",
    },
  ];

  return <div></div>;
};
export default Teachers_test;
