const USERS = [
  {
    id: 1,
    gender: "male",
    pseudo: "Alexandre",
    age: 20,
    picture: "https://randomuser.me/api/portraits/men/29.jpg",
    music: "jazz , blues",
    fav: "Coldplay | Adventure of a Lifetime  &  Adele | Rolling in the Deep ",
  },
  {
    id: 2,
    gender: "male",
    pseudo: "Felix",
    age: 24,
    picture: "https://randomuser.me/api/portraits/men/30.jpg",
    music: "hiphop , rap",
    fav: "Beyoncé | Single Ladies  &  Coldplay | Adventure of a Lifetime ",
  },
  {
    id: 3,
    gender: "male",
    pseudo: "Jack",
    age: 27,
    picture: "https://randomuser.me/api/portraits/men/31.jpg",
    music: "raggae , funk",
    fav: " Bruno Mars | Uptown Funk & Lizzo | Good as Hell ",
  },
  {
    id: 4,
    gender: "male",
    pseudo: "Marc",
    age: 30,
    picture: "https://randomuser.me/api/portraits/men/32.jpg",
    music: "pop , rock",
    fav: " Katy Perry | Firework & The Pixies | Where Is My Mind? ",
  },
  {
    id: 5,
    gender: "male",
    pseudo: "Philippe",
    age: 32,
    picture: "https://randomuser.me/api/portraits/men/33.jpg",
    music: "raggae , jazz",
    fav: " Pharrell Williams | Happy & Miles Davis | All Blues ",
  },
  {
    id: 6,
    gender: "male",
    pseudo: "André",
    age: 35,
    picture: "https://randomuser.me/api/portraits/men/34.jpg",
    music: "classical , electronic",
    fav: " Daft Punk | Get Lucky & Miles Davis | So What ",
  },
  {
    id: 7,
    gender: "male",
    pseudo: "Paul",
    age: 37,
    picture: "https://randomuser.me/api/portraits/men/35.jpg",
    music: "electronic , rock",
    fav: " Martin Solveig | The Night Out & DJ Snake | Turn Down for What ",
  },
  {
    id: 8,
    gender: "male",
    pseudo: "Esteban",
    age: 40,
    picture: "https://randomuser.me/api/portraits/men/36.jpg",
    music: "funk , latin",
    fav: " Marvin Gaye | Got To Give It Up & James Brown | Papas Got A Brand New Bag ",
  },
  {
    id: 9,
    gender: "male",
    pseudo: "Louis",
    age: 45,
    picture: "https://randomuser.me/api/portraits/men/37.jpg",
    music: "soul , country",
    fav: " Amy Winehouse | ReHab & Brad Paisley | Welcome to the Future ",
  },
  {
    id: 10,
    gender: "male",
    pseudo: "Peter",
    age: 70,
    picture: "https://randomuser.me/api/portraits/men/38.jpg",
    music: "blues , rock",
    fav: " Duke Ellington | Take The A Train & Jimi Hendrix | Purple Haze ",
  },
  {
    id: 11,
    gender: "female",
    pseudo: "Clara",
    age: 20,
    picture: "https://randomuser.me/api/portraits/women/30.jpg",
    music: "hiphop , rock",
    fav: " Outkast | Hey Ya! & Led Zeppelin | Whole Lotta Love ",
  },
  {
    id: 12,
    gender: "female",
    pseudo: "Alice",
    age: 25,
    picture: "https://randomuser.me/api/portraits/women/31.jpg",
    music: "funk , rock",
    fav: " The Weeknd | Blinding Lights & Destiny's Child | Bootylicious ",
  },
  {
    id: 13,
    gender: "female",
    pseudo: "Vanessa",
    age: 30,
    picture: "https://randomuser.me/api/portraits/women/32.jpg",
    music: "blues , pop",
    fav: " Lady Gaga | Poker Face & Billie Eilish | Bad Guy ",
  },
  {
    id: 14,
    gender: "female",
    pseudo: "Eve",
    age: 35,
    picture: "https://randomuser.me/api/portraits/women/33.jpg",
    music: "latin , jazz",
    fav: " Shakira | Hips Don't Lie & John Coltrane | My Favorite Things ",
  },
  {
    id: 15,
    gender: "female",
    pseudo: "Mathilde",
    age: 37,
    picture: "https://randomuser.me/api/portraits/women/34.jpg",
    music: "electronic , country",
    fav: " David Guetta | Titanium & Duck Sauce | Barbra Streisand ",
  },
  {
    id: 16,
    gender: "female",
    pseudo: "Elsa",
    age: 40,
    picture: "https://randomuser.me/api/portraits/women/35.jpg",
    music: "pop , rock",
    fav: " Justin Timberlake | SexyBack  & The Rolling Stones | Sympathy for the Devil ",
  },
  {
    id: 17,
    gender: "female",
    pseudo: "Louise",
    age: 45,
    picture: "https://randomuser.me/api/portraits/women/36.jpg",
    music: "raggae , rock",
    fav: " Nicki Minaj | Starships & Bob Marley | Bob Marley ",
  },
  {
    id: 18,
    gender: "female",
    pseudo: "Anaïs",
    age: 49,
    picture: "https://randomuser.me/api/portraits/women/37.jpg",
    music: "pop , latin",
    fav: " Gwen Stefani | Hollaback Girl & Marc Anthony | Ahora Quien ",
  },
  {
    id: 19,
    gender: "female",
    pseudo: "Suzie",
    age: 54,
    picture: "https://randomuser.me/api/portraits/women/38.jpg",
    music: "hiphop , funk",
    fav: " Eve | Let Me Blow Ya Mind & Otto Knows | Million Voices ",
  },
  {
    id: 20,
    gender: "female",
    pseudo: "Vicky",
    age: 32,
    picture: "https://randomuser.me/api/portraits/women/39.jpg",
    music: "classical , jazz",
    fav: " Lorde | Royals & Gnarls Barkley | Crazy ",
  },
  {
    id: 21,
    gender: "male",
    pseudo: "Alexandre",
    age: 20,
    picture: "https://randomuser.me/api/portraits/men/50.jpg",
    music: "jazz , blues",
    fav: "Coldplay | Adventure of a Lifetime  &  Adele | Rolling in the Deep ",
  },
  {
    id: 22,
    gender: "male",
    pseudo: "Felix",
    age: 24,
    picture: "https://randomuser.me/api/portraits/men/51.jpg",
    music: "hiphop , rap",
    fav: "Beyoncé | Single Ladies  &  Coldplay | Adventure of a Lifetime ",
  },
  {
    id: 23,
    gender: "male",
    pseudo: "Jack",
    age: 27,
    picture: "https://randomuser.me/api/portraits/men/52.jpg",
    music: "raggae , funk",
    fav: " Bruno Mars | Uptown Funk & Lizzo | Good as Hell ",
  },
  {
    id: 24,
    gender: "male",
    pseudo: "Marc",
    age: 30,
    picture: "https://randomuser.me/api/portraits/men/53.jpg",
    music: "pop , rock",
    fav: " Katy Perry | Firework & The Pixies | Where Is My Mind? ",
  },
  {
    id: 25,
    gender: "male",
    pseudo: "Philippe",
    age: 32,
    picture: "https://randomuser.me/api/portraits/men/54.jpg",
    music: "raggae , jazz",
    fav: " Pharrell Williams | Happy & Miles Davis | All Blues ",
  },
  {
    id: 26,
    gender: "male",
    pseudo: "André",
    age: 35,
    picture: "https://randomuser.me/api/portraits/men/55.jpg",
    music: "classical , electronic",
    fav: " Daft Punk | Get Lucky & Miles Davis | So What ",
  },
  {
    id: 27,
    gender: "male",
    pseudo: "Paul",
    age: 37,
    picture: "https://randomuser.me/api/portraits/men/56.jpg",
    music: "electronic , rock",
    fav: " Martin Solveig | The Night Out & DJ Snake | Turn Down for What ",
  },
  {
    id: 28,
    gender: "male",
    pseudo: "Esteban",
    age: 40,
    picture: "https://randomuser.me/api/portraits/men/57.jpg",
    music: "funk , latin",
    fav: " Marvin Gaye | Got To Give It Up & James Brown | Papas Got A Brand New Bag ",
  },
  {
    id: 29,
    gender: "male",
    pseudo: "Louis",
    age: 45,
    picture: "https://randomuser.me/api/portraits/men/58.jpg",
    music: "soul , country",
    fav: " Amy Winehouse | ReHab & Brad Paisley | Welcome to the Future ",
  },
  {
    id: 30,
    gender: "male",
    pseudo: "Peter",
    age: 70,
    picture: "https://randomuser.me/api/portraits/men/59.jpg",
    music: "blues , rock",
    fav: " Duke Ellington | Take The A Train & Jimi Hendrix | Purple Haze ",
  },
  {
    id: 31,
    gender: "female",
    pseudo: "Clara",
    age: 20,
    picture: "https://randomuser.me/api/portraits/women/40.jpg",
    music: "hiphop , rock",
    fav: " Outkast | Hey Ya! & Led Zeppelin | Whole Lotta Love ",
  },
  {
    id: 32,
    gender: "female",
    pseudo: "Alice",
    age: 25,
    picture: "https://randomuser.me/api/portraits/women/41.jpg",
    music: "funk , rock",
    fav: " The Weeknd | Blinding Lights & Destiny's Child | Bootylicious ",
  },
  {
    id: 33,
    gender: "female",
    pseudo: "Vanessa",
    age: 30,
    picture: "https://randomuser.me/api/portraits/women/42.jpg",
    music: "blues , pop",
    fav: " Lady Gaga | Poker Face & Billie Eilish | Bad Guy ",
  },
  {
    id: 34,
    gender: "female",
    pseudo: "Eve",
    age: 35,
    picture: "https://randomuser.me/api/portraits/women/43.jpg",
    music: "latin , jazz",
    fav: " Shakira | Hips Don't Lie & John Coltrane | My Favorite Things ",
  },
  {
    id: 35,
    gender: "female",
    pseudo: "Mathilde",
    age: 37,
    picture: "https://randomuser.me/api/portraits/women/44.jpg",
    music: "electronic , country",
    fav: " David Guetta | Titanium & Duck Sauce | Barbra Streisand ",
  },
  {
    id: 36,
    gender: "female",
    pseudo: "Elsa",
    age: 40,
    picture: "https://randomuser.me/api/portraits/women/45.jpg",
    music: "pop , rock",
    fav: " Justin Timberlake | SexyBack  & The Rolling Stones | Sympathy for the Devil ",
  },
  {
    id: 37,
    gender: "female",
    pseudo: "Louise",
    age: 45,
    picture: "https://randomuser.me/api/portraits/women/46.jpg",
    music: "raggae , rock",
    fav: " Nicki Minaj | Starships & Bob Marley | Bob Marley ",
  },
  {
    id: 38,
    gender: "female",
    pseudo: "Anaïs",
    age: 49,
    picture: "https://randomuser.me/api/portraits/women/47.jpg",
    music: "pop , latin",
    fav: " Gwen Stefani | Hollaback Girl & Marc Anthony | Ahora Quien ",
  },
  {
    id: 39,
    gender: "female",
    pseudo: "Suzie",
    age: 54,
    picture: "https://randomuser.me/api/portraits/women/48.jpg",
    music: "hiphop , funk",
    fav: " Eve | Let Me Blow Ya Mind & Otto Knows | Million Voices ",
  },
  {
    id: 40,
    gender: "female",
    pseudo: "Vicky",
    age: 32,
    picture: "https://randomuser.me/api/portraits/women/49.jpg",
    music: "classical , jazz",
    fav: " Lorde | Royals & Gnarls Barkley | Crazy ",
  },
  {
    id: 41,
    gender: "male",
    pseudo: "Alexandre",
    age: 20,
    picture: "https://randomuser.me/api/portraits/men/60.jpg",
    music: "jazz , blues",
    fav: "Coldplay | Adventure of a Lifetime  &  Adele | Rolling in the Deep ",
  },
  {
    id: 42,
    gender: "male",
    pseudo: "Felix",
    age: 24,
    picture: "https://randomuser.me/api/portraits/men/61.jpg",
    music: "hiphop , rap",
    fav: "Beyoncé | Single Ladies  &  Coldplay | Adventure of a Lifetime ",
  },
  {
    id: 43,
    gender: "male",
    pseudo: "Jack",
    age: 27,
    picture: "https://randomuser.me/api/portraits/men/62.jpg",
    music: "raggae , funk",
    fav: " Bruno Mars | Uptown Funk & Lizzo | Good as Hell ",
  },
  {
    id: 44,
    gender: "male",
    pseudo: "Marc",
    age: 30,
    picture: "https://randomuser.me/api/portraits/men/63.jpg",
    music: "pop , rock",
    fav: " Katy Perry | Firework & The Pixies | Where Is My Mind? ",
  },
  {
    id: 45,
    gender: "male",
    pseudo: "Philippe",
    age: 32,
    picture: "https://randomuser.me/api/portraits/men/64.jpg",
    music: "raggae , jazz",
    fav: " Pharrell Williams | Happy & Miles Davis | All Blues ",
  },
  {
    id: 46,
    gender: "male",
    pseudo: "André",
    age: 35,
    picture: "https://randomuser.me/api/portraits/men/65.jpg",
    music: "classical , electronic",
    fav: " Daft Punk | Get Lucky & Miles Davis | So What ",
  },
  {
    id: 47,
    gender: "male",
    pseudo: "Paul",
    age: 37,
    picture: "https://randomuser.me/api/portraits/men/66.jpg",
    music: "electronic , rock",
    fav: " Martin Solveig | The Night Out & DJ Snake | Turn Down for What ",
  },
  {
    id: 48,
    gender: "male",
    pseudo: "Esteban",
    age: 40,
    picture: "https://randomuser.me/api/portraits/men/67.jpg",
    music: "funk , latin",
    fav: " Marvin Gaye | Got To Give It Up & James Brown | Papas Got A Brand New Bag ",
  },
  {
    id: 49,
    gender: "male",
    pseudo: "Louis",
    age: 45,
    picture: "https://randomuser.me/api/portraits/men/68.jpg",
    music: "soul , country",
    fav: " Amy Winehouse | ReHab & Brad Paisley | Welcome to the Future ",
  },
  {
    id: 50,
    gender: "male",
    pseudo: "Peter",
    age: 70,
    picture: "https://randomuser.me/api/portraits/men/69.jpg",
    music: "blues , rock",
    fav: " Duke Ellington | Take The A Train & Jimi Hendrix | Purple Haze ",
  },
  {
    id: 51,
    gender: "female",
    pseudo: "Clara",
    age: 20,
    picture: "https://randomuser.me/api/portraits/women/70.jpg",
    music: "hiphop , rock",
    fav: " Outkast | Hey Ya! & Led Zeppelin | Whole Lotta Love ",
  },
  {
    id: 52,
    gender: "female",
    pseudo: "Alice",
    age: 25,
    picture: "https://randomuser.me/api/portraits/women/71.jpg",
    music: "funk , rock",
    fav: " The Weeknd | Blinding Lights & Destiny's Child | Bootylicious ",
  },
  {
    id: 53,
    gender: "female",
    pseudo: "Vanessa",
    age: 30,
    picture: "https://randomuser.me/api/portraits/women/72.jpg",
    music: "blues , pop",
    fav: " Lady Gaga | Poker Face & Billie Eilish | Bad Guy ",
  },
  {
    id: 54,
    gender: "female",
    pseudo: "Eve",
    age: 35,
    picture: "https://randomuser.me/api/portraits/women/73.jpg",
    music: "latin , jazz",
    fav: " Shakira | Hips Don't Lie & John Coltrane | My Favorite Things ",
  },
  {
    id: 55,
    gender: "female",
    pseudo: "Mathilde",
    age: 37,
    picture: "https://randomuser.me/api/portraits/women/74.jpg",
    music: "electronic , country",
    fav: " David Guetta | Titanium & Duck Sauce | Barbra Streisand ",
  },
  {
    id: 56,
    gender: "female",
    pseudo: "Elsa",
    age: 40,
    picture: "https://randomuser.me/api/portraits/women/75.jpg",
    music: "pop , rock",
    fav: " Justin Timberlake | SexyBack  & The Rolling Stones | Sympathy for the Devil ",
  },
  {
    id: 57,
    gender: "female",
    pseudo: "Louise",
    age: 45,
    picture: "https://randomuser.me/api/portraits/women/76.jpg",
    music: "raggae , rock",
    fav: " Nicki Minaj | Starships & Bob Marley | Bob Marley ",
  },
  {
    id: 58,
    gender: "female",
    pseudo: "Anaïs",
    age: 49,
    picture: "https://randomuser.me/api/portraits/women/77.jpg",
    music: "pop , latin",
    fav: " Gwen Stefani | Hollaback Girl & Marc Anthony | Ahora Quien ",
  },
  {
    id: 59,
    gender: "female",
    pseudo: "Suzie",
    age: 54,
    picture: "https://randomuser.me/api/portraits/women/78.jpg",
    music: "hiphop , funk",
    fav: " Eve | Let Me Blow Ya Mind & Otto Knows | Million Voices ",
  },
  {
    id: 60,
    gender: "female",
    pseudo: "Vicky",
    age: 32,
    picture: "https://randomuser.me/api/portraits/women/79.jpg",
    music: "classical , jazz",
    fav: " Lorde | Royals & Gnarls Barkley | Crazy ",
  },
];

export default USERS;
